### ISSUE TITLE
В сцене отсутствуют элементы

### ISSUE THREAD

**Issue by mkukarin01** [iddqdPro/flappybat#1]
Привет, хотел покрутить игрушку, при загрузке в кокос-креатор, кажется как будто канвас ничего не содержит, хотя изначально там создавались всякие штуки - лейбл и тд
<img width="345" alt="Screenshot 2023-05-16 at 20 54 12" src="https://github.com/iddqdPro/flappybat/assets/71261064/08c13628-a5d7-4a3c-8a21-d79e09519803">

**Comment by fixityy** [comment]
Привет! Необходимо открыть нужную сцену в панели ассетов (внизу слева). 
После первой загрузки кокос открывают новую пустую сцену.
<img width="206" alt="Снимок экрана 2023-05-17 в 10 40 38" src="https://github.com/iddqdPro/flappybat/assets/98152482/12fd3626-18c8-468f-b679-81ca954fb2b1">
